### ISSUE TITLE
keyword incorrect 

### ISSUE THREAD

**Issue by EricAugust** [HazyResearch/hyperbolics#5]
Traceback (most recent call last):
  File "pytorch/pytorch_hyperbolic.py", line 393, in <module>
    _parser.dispatch()
  File "/opt/conda/lib/python3.6/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/opt/conda/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/opt/conda/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "pytorch/pytorch_hyperbolic.py", line 302, in learn
    m       = cudaify( Hyperbolic_Emb(G.order(), rank, initialize=m_init, learn_scale=learn_scale, exponential_rescale=exponential_rescale) )
  File "/root/hyperbolics/pytorch/hyperbolic_models.py", line 84, in __init__
    self.w = Hyperbolic_Parameter(x)
  File "/root/hyperbolics/pytorch/hyperbolic_parameter.py", line 12, in __new__
    ret =  super(nn.Parameter, cls).__new__(cls, data, requires_grad=requires_grad)
TypeError: new() received an invalid combination of arguments - got (Tensor, requires_grad=bool), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the keywords were incorrect: requires_grad
 * (object data, torch.device device)
      didn't match because some of the keywords were incorrect: requires_grad

**Comment by albertfgu** [comment]
This should be caused by the Pytorch version upgrade (codebase was previously on 0.3). Should work now.
